name: tracking-location-annotation

channels:
  - conda-forge

dependencies:
  - python=3.9.10
  - google-cloud-bigquery[pandas]==2.34.0
  - python-dateutil=2.8.2
  - pydantic=1.9.0
  - python-dotenv=0.19.2
  - pandas=1.4.1
  - python-kubernetes=23.3.0
  - tqdm==4.64.0
  - metaflow==2.6.0
  - pandas-stubs==1.2.0.57
  - google-cloud-storage==2.1.0
  # test
  - pytest=7.1.1
  - pytest-cov=3.0.0
  - pytest-env=0.6.2
  - coverage=6.3.1
  - freezegun=1.1.0
  - mypy=0.942
  - testfixtures=6.18.3

  - pip=21.3.1
  - pip:
    - -r requirements.txt
